Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
X = pd.DataFrame(df.data, columns=df.feature_names)
X = X[['mean area', 'mean compactness']]
y = pd.Categorical.from_codes(df.target, df.target_names)
y = pd.get_dummies(y, drop_first=True)
------------------

[0;31m[0m
[0;31mAttributeError[0mTraceback (most recent call last)
[0;32m<ipython-input-4-747952eac34b>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mX[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mdf[0m[0;34m.[0m[0mdata[0m[0;34m,[0m [0mcolumns[0m[0;34m=[0m[0mdf[0m[0;34m.[0m[0mfeature_names[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mX[0m [0;34m=[0m [0mX[0m[0;34m[[0m[0;34m[[0m[0;34m'mean area'[0m[0;34m,[0m [0;34m'mean compactness'[0m[0;34m][0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0my[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mCategorical[0m[0;34m.[0m[0mfrom_codes[0m[0;34m([0m[0mdf[0m[0;34m.[0m[0mtarget[0m[0;34m,[0m [0mdf[0m[0;34m.[0m[0mtarget_names[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0my[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mget_dummies[0m[0;34m([0m[0my[0m[0;34m,[0m [0mdrop_first[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py[0m in [0;36m__getattr__[0;34m(self, name)[0m
[1;32m   5485[0m         ):
[1;32m   5486[0m             [0;32mreturn[0m [0mself[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5487[0;31m         [0;32mreturn[0m [0mobject[0m[0;34m.[0m[0m__getattribute__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   5488[0m [0;34m[0m[0m
[1;32m   5489[0m     [0;32mdef[0m [0m__setattr__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m:[0m [0mstr[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m [0;34m->[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'DataFrame' object has no attribute 'data'
AttributeError: 'DataFrame' object has no attribute 'data'

